blank_issues_enabled: false
contact_links:
  - name: Sigstore Slack
    url: https://join.slack.com/t/sigstore/shared_invite/zt-47srvpyn6-j8Ek5hGBwKN32IjLw8BvYA
    about: Also consider our Slack channel. It's the quickest way to have a conversation with the developers!
